
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import Header from "./components/Header";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  


  return (
    <html lang="en" >
       {/* ${
          theme === "dark" ? " text-[#ffffff]" : "bg-[#ffffff] text-[#000000]"
        } */}
      <body
        className={`transition-colors duration-300  dark:bg-[#0E1011] dark:text-[#ffffff]`}
      >
        <Toaster />
        <Header />
        
        {children}
      </body>
    </html>
  );
}
